language: node_js
node_js:
  - 10.10.0
install:
  - yarn
deploy:
  provider: script
  script: deploy.sh
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^staging|master|set-up-travis$
