language: node_js
node_js:
  - 10.10.0
install:
  - yarn
deploy:
  provider: firebase
  project: shire-production
  on:
    branch: master
  skip_cleanup: true
  token:
    secure: jWQ4HMsK8fMgG9b66ouHcH5Ms96Tc2ZWmpGMtSQXWv1LXzlHrDuz21wNWcLEogwEdLMYbz9uctgh7dN5h6zz6YnzVJWk+O0TkyY2kfNedHdDphlL8WOBLmCmm1u90KLjQc10kC776VLqPBnmh57XYoqIZ1q6YufyvH74aiFkD57vcv30H6k23qvayqe5E6mG4q81ntDtQLh15Y3ilkrRJleEGosNubOPGUdnWMM0MU67NgNQahiKozj5nU+rVe6+SvGINC7ZZOh3TWz2IJuFaQIYv2FN56NdwGwSHe828q7T7FWxN1w+UyvPZgjjjD2tADcTGMhNxMVyd8Js3y/jx0/Bl5zUYJKxs5Cj/asJAL3x/78RHHO06Jaz/OpG0JIrzxJ1QnGcOqPeAXyzkiDRgxNA3bqy9+F4MUyYWjIxp9V9XcXKS8yjJV82Bl339twtn83svXT2ej3/V/YyCv3v2aYkXZ0tEXCFBAhhY4lIeBRs7mHqO/CLO1v/zfK+LjpTjS2ZduoyfymMqeXSeYLNuvIvNfWOgi83L052ZXmdPXpBLMYOdsvvuWGGvLtfoZQtutDvkZF2L7wpFxRxR1lUpGd8KcS0ER2J2WMKb0lvTF6yArK6kFf1gsYK3u3LGcLyHOjmVPSUIvOY7ZbKo1Iefmlu2ghDtFOQy6f59pWBA0I=
