language: node_js
node_js:
  - 10.10.0
install:
  - yarn
deploy:
  provider: script
  script: 'openssl aes-256-cbc -K $encrypted_b78d8c79679e_key -iv $encrypted_b78d8c79679e_iv
    -in secrets.zip.enc -out secrets.zip -d && unzip secrets.zip && ./deploy.sh'
  skip_cleanup: true
  on:
    all_branches: true
    condition: '$TRAVIS_BRANCH =~ ^staging|master$'
