language: node_js
node_js:
  - 10.10.0
install:
  - yarn
deploy:
  provider: script
  script: 'openssl aes-256-cbc -K $encrypted_5880cf525281_key -iv $encrypted_5880cf525281_iv -in secrets.zip.enc -out secrets.zip -d && ./deploy.sh'
  skip_cleanup: true
  on:
    all_branches: true
    condition: '$TRAVIS_BRANCH =~ ^staging|master|set-up-travis$'
